apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
      - ./infra/k8s/*
build: 
  local:
    push: false
  artifacts:
    - image: ranan98/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ranan98/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: ranan98/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: ranan98/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: ranan98/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: ranan98/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .